[build-system]
requires = ["setuptools"]

[tool.isort]
profile = "black"
combine_as_imports = true
known_first_party = [
  "bhtools",
]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
